### ISSUE TITLE
[Tech]: Change subscription approach on Swap screen

### ISSUE THREAD

**Issue by arvifox** [sora-xor/sora-android#236]
### Problem statement

Current subscription is a time-based polling, which is inefficient. Blockchain state subscription is a better way.

### Definition of Done

Swap quote calculation is based on subscription.

**Comment by Trezeguet1** [comment]
Verified on Sora Develop 3.8.0.0-firebase (160) version.

Only the logic for executing the quote request has changed.
Previously it was every 5 seconds, but now it’s a subscription for each block.

![telegram-cloud-photo-size-2-5355315707325304762-y](https://github.com/sora-xor/sora-android/assets/51509139/f9c56442-f364-440b-8421-10da561b662f)

**There are no Min Received and Network fee and conversion of tokens because the quota is not reached.**

**Comment by Trezeguet1** [comment]
It looks like we are only displaying what comes from the network.
